import Head from "next/head";
import { useState } from "react";
import Count from "@/component/count";
import Movies from "@/component/movies";
import Link from "next/link";
import MyNav from "@/component/nav";

interface IMovie {
  _id: string;
  plot: string;
  genres: [string];
  runtime: number;
  cast: [string];
  num_mflix_comments: number;
  poster: string;
  title: string;
  fullplot: string;
  languages: [string];
  released: Date;
  directors: [string];
  rated: string;
  awards: {
    wins: number;
    nominations: number;
    text: string;
  };
  lastupdated: string;
  year: number;
  imdb: {
    rating: number;
    votes: number;
    id: number;
  };
  countries: [];
  type: string;
  tomatoes: {
    viewer: {
      rating: number;
      numReviews: number;
      meter: number;
    };
    lastUpdated: Date;
  };
}

export default function Home({
  movies,
  pagination,
}: {
  movies: IMovie[];
  pagination: any;
}) {
  const [filter, setFilter] = useState("");
  const [page, setPage] = useState(1);

  return (
    <div>
      <Head>
        <title>Movie Review</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <MyNav setFilter={setFilter} />
        <div className="flex justify-center bg-gray-100 pt-12">
          <Movies movies={movies} filter={filter} pagination={pagination} />
        </div>
      </div>
    </div>
  );
}

export async function getServerSideProps(ctx: any) {
  const { limit, page } = ctx.query;
  const res = await fetch(
    `http://localhost:8022/movies?limit=${limit || 10}&page=${page || 1}`
  );
  const data = await res.json();
  const pagination = data.pagination;
  return {
    props: { movies: data.movies, pagination },
  };
}
