import Head from "next/head";
import { useState } from "react";
import Count from "@/component/count";
import Movies from "@/component/movies";

export default function Home() {
  const [count, setCount] = useState(0);
  return (
    <>
      <Head>
        <title>Movie Review</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Welcome to our website by next.js</h1>
        <Count />
        <Movies />
      </div>
    </>
  );
}
